development:
  adapter: postgresql
  database: drinkee-development

test:
  adapter: postgresql
  database: drinkee-test

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
